name: Deploy to GitHub Pages

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install deps
        run: |
          npm ci || npm i
      - name: Write version.txt
        run: |
          VERSION="${GITHUB_REF_NAME}"
          echo "$VERSION" > public/version.txt
      - name: Build
        env:
          VITE_APP_VERSION: ${{ github.ref_name }}
        run: npm run build
      - name: Verify version.txt in dist
        run: |
          ls -la dist || true
          if [ ! -f dist/version.txt ]; then
            echo "ERROR: dist/version.txt is missing. Ensure Vite publicDir includes public/version.txt." >&2
            exit 1
          fi
          echo "version.txt contents:" && cat dist/version.txt
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
